import { expect, test } from "@playwright/test";

test("no-signup demo crosses sports, weather, abstention and measured simulation", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("/");
  await expect(page.getByRole("heading", { level: 1 })).toBeVisible();
  await page.getByRole("button", { name: /try (the )?demo/i }).or(page.getByRole("link", { name: /try (the )?demo/i })).first().click();
  await expect(page).toHaveURL(/\/onboarding/);
  for (let step = 0; step < 3; step++) await page.getByRole("button", { name: /continue/i }).click();
  await page.getByRole("button", { name: /start agent/i }).click();
  await expect(page.getByRole("heading", { name: "Your snapshot is ready." })).toBeVisible();
  await page.getByRole("button", { name: /open workspace/i }).click();
  await expect(page).toHaveURL(/\/dashboard/);
  await expect(page.getByText(/DEMO DATA/i).first()).toBeVisible();
  await expect(page.locator("main").getByText(/simulation/i).first()).toBeVisible();
  await expect(page.locator("main").getByText(/Warriors/i).first()).toBeVisible();
  await expect(page.locator("main").getByText(/San Francisco/i).first()).toBeVisible();
  await expect(page.locator("main").getByText(/uncertainty/i).first()).toBeVisible();
  await page.goto("/forecasts");
  await expect(page.getByText(/Warriors/i).first()).toBeVisible();
  await expect(page.getByText(/San Francisco/i).first()).toBeVisible();
  const forecast = page.locator(".forecast-row").first();
  await expect(forecast.locator(".forecast-evidence")).toContainText("Risk");
  await expect(forecast.locator(".forecast-evidence")).toContainText("Uncertainty");
  await expect(forecast.locator(".forecast-reference")).toBeVisible();
  await expect(forecast.locator(".forecast-gap")).toBeVisible();
  await page.locator('a[href^="/forecast/"]').filter({ hasText: /Warriors/i }).first().click();
  await expect(page).toHaveURL(/\/forecast\//);
  await expect(page.getByText(/uncertainty/i).first()).toBeVisible();
  await page.goto("/forecasts");
  await page.locator('a[href^="/forecast/"]').filter({ hasText: /San Francisco/i }).first().click();
  await expect(page).toHaveURL(/\/forecast\//);
  await page.goto("/forecasts");
  await page.getByRole("button", { name: /abstained/i }).click();
  await expect(page.getByText(/uncertain/i).first()).toBeVisible();
  await page.goto("/portfolio");
  await expect(page.getByText(/DEMO DATA/i).first()).toBeVisible();
  const position = page.locator(".ledger-table tbody tr").first();
  const positionHref = await position.locator("a.table-event").getAttribute("href");
  const allocation = await position.locator('[data-label="Virtual allocation"]').textContent();
  await page.goto("/history");
  await expect(page.getByText(/DEMO DATA/i).first()).toBeVisible();
  const decision = page.locator(".history-table tbody tr").filter({ has: page.locator(`a.table-event[href="${positionHref}"]`) });
  await expect(decision.locator('[data-label="Allocation"]')).toHaveText(allocation!.trim());
  await expect(page.locator(".history-table tbody tr").filter({ has: page.locator(".decision-no") }).first().locator('[data-label="Allocation"]')).toHaveText("No position");
  await page.goto("/performance");
  await expect(page.getByText(/DEMO DATA/i).first()).toBeVisible();
  await expect(page.getByText(/Brier/i).first()).toBeVisible();
  expect(errors).toEqual([]);
});

test("invalid saved ledger is rejected instead of displaying corrupted credits", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("/");
  await page.getByRole("button", { name: /try (the )?demo/i }).first().click();
  for (let step = 0; step < 3; step++) await page.getByRole("button", { name: /continue/i }).click();
  await page.getByRole("button", { name: /start agent/i }).click();
  await page.getByRole("button", { name: /open workspace/i }).click();
  await expect(page).toHaveURL(/\/dashboard/);
  await page.evaluate(() => {
    const key = "forecast-studio-demo-v1";
    const snapshot = JSON.parse(localStorage.getItem(key)!);
    snapshot.run.positions[0].virtualAllocation = -40;
    localStorage.setItem(key, JSON.stringify(snapshot));
  });
  await page.reload();
  await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem("forecast-studio-demo-v1")!).run)).toBeNull();
  await expect(page.getByRole("link", { name: /set up your agent/i })).toBeVisible();
  expect(errors).toEqual([]);
});

test("configured review run shows real scan snapshot before the workspace", async ({ page }) => {
  await page.goto("/onboarding");
  await page.getByRole("button", { name: /continue/i }).click();
  await page.getByRole("button", { name: /continue/i }).click();
  await page.getByRole("button", { name: /15–39%/i }).click();
  await page.getByRole("checkbox").uncheck();
  await page.getByRole("button", { name: /continue/i }).click();
  await expect(page.getByText(/high · 15–39%/i)).toBeVisible();
  await page.getByRole("textbox", { name: /what should your agent follow/i }).fill("Warriors");
  await page.getByRole("button", { name: /start agent/i }).click();
  await expect(page.getByRole("heading", { name: "Your snapshot is ready." })).toBeVisible();
  await expect(page.getByRole("definition")).toHaveCount(4);
  await page.getByRole("button", { name: /open workspace/i }).click();
  await expect(page).toHaveURL(/\/dashboard/);
  await expect(page.getByText(/HIGH RISK · SPORTS \+ WEATHER · REVIEW/i)).toBeVisible();
  await page.goto("/forecasts");
  await expect(page.getByText(/Warriors/i).first()).toBeVisible();
  await expect(page.getByText(/San Francisco stays dry/i)).toHaveCount(0);
  await page.goto("/portfolio");
  await expect(page.getByText(/No positions were created/i)).toBeVisible();
});
